name: ETFUnfreezer
main: net.unserversinley.etfunfreezer.Main
version: 1.0.0
author: Cascaseno
api-version: 1.17
description: Fix frozen entities after removing EntityTrackerFixer.
commands:
  etfu:
    description: Main command of ETFUnfreezer.
    usage: /etfu
permissions:
  etfunfreezer.*:
    children:
      - etfunfreezer.commands
  etfunfreezer.commands:
    default: op